### ISSUE TITLE
Can't read messages from a stream with ioredis@5.0.6

### ISSUE THREAD

**Issue by dardanos** [danthegoodman1/node-redis-streams#1]
I have a stream that I'm trying to read with this library but I'm running into issues

### Redis

I know the stream exists, the consumer group exists, and there is data in the stream
<img width="1340" alt="image" src="https://user-images.githubusercontent.com/52110045/178643083-94e004d3-ed89-41d6-9697-7254a9a0b60e.png">

The consumer group
<img width="1312" alt="image" src="https://user-images.githubusercontent.com/52110045/178643098-7c8dd88c-050e-4aa1-ac21-b29d5c89f694.png">

### Consumer
```ts
// I know this client works
const redisClient = client.duplicate();

const streamConsumer = new Consumer({
  consumerName: 'my-consumer-1',
  groupName: 'orchestrator',
  readItems: 10,
  recordHandler: async (record) => {
    console.log(`[redis-stream] Processing key: ${record.recordID}`);
  },
  errorHandler: async (record) => {
    console.log(`[redis-stream] Error processing ${record.recordID}`);
  },
  redisClient,
  streamName: 'expired-stream,
  blockIntervalMS: 1000,
  checkAbandonedMS: 10000,
});

await streamConsumer.StartConsuming();
console.log('[redis-stream] Started consuming messages');
```

### Output
```
[redis-stream] Started consuming messages
```

I spent time looking at the code (which is really good 👏 ) and I can't find the reason why this is not working.

Could this be related to the new ioredis major version?
Any idea?

**Comment by danthegoodman1** [comment]
@dardanos thanks for the report, what version of ioredis are you running? If it's 5.X that could be it, I have not checked for any incompatibilities with that, so if they've made changes to the functions that are used that could very well be the case.

**Comment by dardanos** [comment]
It's ioredis@5.0.6. I added that to the issue title for reference.

If you think that's the case I can try creating a PR for this @danthegoodman1

**Comment by danthegoodman1** [comment]
Probably, they might’ve changed the api. Feel free to pr! I won’t have time to play with it until next week to find a fix.

**Comment by dardanos** [comment]
Nevermind @danthegoodman1 it's working :) I just had to get more than 10 elements in the stream.
